# Note! If you're using jekyll serve --watch to run a server, you'll need to restart after any changes here
name: "The Code Manual"
description: "It always seems impossible until its done - Nelson Mandela"
# markdown:    kramdown
highlighter: rouge
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#excerpt_separator: "<!--more-->"

#Debug flags
future: false

# Google services
google_analytics: UA-88818077-1

# Disqus post comments
disqus_shortname: thecodemanual

owner: "Krzysztof Madej"
email: "krzysztof.madej.1987@gmail.com"
twitter: ""
github: "ExoltenOne"
facebook: ""
linkedin: "https://pl.linkedin.com/in/krzysztof-madej"
# the following really long number is what you find in https://plus.google.com/your-really-long-id/posts
googleplus: 111111111111111111
location:
phone: 555-555-5555
skype: your.username

# Outputting
permalink: /post/:title/
paginate: 5
paginate_path: '/blog/page/:num/'
timezone: Europe/Berlin

# Where things are
collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
    output: true
    permalink: /blog/tag/:name/

defaults:
  - scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category
  - scope:
      path: ""
      type: my_tags
    values:
      layout: blog_by_tag
